export const ADD_PROJECT = 'ADD_PROJECT';
export const SET_OPTIONS = 'SET_OPTIONS';
export const UPDATE_CURRENT = 'UPDATE_CURRENT';


export const UPDATE_VIEW_PRIVATE_MENU = 'UPDATE_VIEW_PRIVATE_MENU';
export const UPDATE_VIEW_PRIVATE_CONTENT = 'UPDATE_VIEW_PRIVATE_CONTENT';
export const UPDATE_CURRENT_PRIVATE = 'UPDATE_CURRENT_PRIVATE';
